### ISSUE TITLE
Stable release version

### ISSUE THREAD

**Issue by SebaDro** [neuralhydrology/neuralhydrology#20]
Hi,

I'm planning to use your great library for my studies on modelling rainfall-runoff. Since there is only a master branch in this repository, I was wondering whether the master branch is stable or also contains some code that is still under development and not yet tested as stable. Maybe, a basic versioning strategy would be very helpful to be able to assess the reliability of certain features. 

What do you think about it?

**Comment by kratzert** [comment]
Hi @SebaDro,

you are right, that there exists only a master branch in this repository. The reason is that the research and development is happening in a different, private repository. From there, we push updates to this public repository. For obvious reasons, we can't have all of our research code on a public repository before the results are somehow published. That is the reason for this two split. However, as we did so far, we push every new feature as well as tutorials etc. quite regularly to this public repository. In fact, two new examples and some model extensions are about to be released within the next days/hours (one of which might bring slight incompatibilities with models trained with older versions).

We also have a concrete plan for the v.1.0 release, which will happen within the next month, which will cover a lot of additional features. From there on, we will (try to) no have any updates that break backwards compatibility until an eventual next major release.

Starting with v.1.0 we will also add release tags + channel log here on GitHub. We already have version numbering so far, but right now we are mostly counting until v.1.0.

I hope that helps you. If you have any other question, let me know.

P.S.: What is your research about? Cool that you decided to use this library as part of it.

**Comment by SebaDro** [comment]
Hey @kratzert, thanks for your prompt reply.

Great to hear, that the library is still under active development. I understand, that publishing your research code, which may have not been reviewed so far, could be counterproductive to your research efforts. So the two split seems reasonable. Nevertheless, I'm looking forward to the new features in the next release.

> Starting with v.1.0 we will also add release tags + channel log here on GitHub. We already have version numbering so far, but right now we are mostly counting until v.1.0.

I noticed the version hints within your commit messages. So, adding release tags would have also been my suggestion, since it facilitates the use of your library. Otherwise, anyone who wants to work with a certain version, must checkout a specific commit from the master branch. But great to hear, that you are already planning such a versioning strategy with the upcoming major release. 



P.S.: We analyse the impact of land cover change on rainfall-runoff modelling using deep learning. Your Enity Aware LSTM seems very helpful for this task.

**Comment by kratzert** [comment]
That sounds interesting. Looking forward to read more on that. 

If you have any other suggestion for usability of this library, let me know. Feedback is always highly welcomed. I will close this issue for now but feel free to reopen.
