### ISSUE TITLE
`datautils.utils.infer_frequency`: `pd.infer_freq()` may produce result which `pd.to_timedelta()` can't handle

### ISSUE THREAD

**Issue by NHoose** [neuralhydrology/neuralhydrology#30]
Hi all,
I'm trying to use you library with a dataset of my own but encountered the following error:
```
c:\users\nikolas hoose\documents\programmieren\neuralhydrology\neuralhydrology\datasetzoo\basedataset.py in _load_or_create_xarray_dataset(self)
    279                 end_dates = [date + pd.Timedelta(days=1, seconds=-1) for date in self.dates[basin]["end_dates"]]
    280 
--> 281                 native_frequency = utils.infer_frequency(df.index)
    282                 if not self.frequencies:
    283                     self.frequencies = [native_frequency]  # use df's native resolution by default

c:\users\nikolas hoose\documents\programmieren\neuralhydrology\neuralhydrology\datautils\utils.py in infer_frequency(index)
    166     if native_frequency[0] not in '0123456789':  # add a value to the unit so to_timedelta works
    167         native_frequency = f'1{native_frequency}'
--> 168     if pd.to_timedelta(native_frequency) == pd.to_timedelta(0):
    169         raise ValueError('Inferred dataset frequency is zero.')
    170     return native_frequency

~\.conda\envs\nh4gruv\lib\site-packages\pandas\core\tools\timedeltas.py in to_timedelta(arg, unit, errors)
    130 
    131     # ...so it must be a scalar value. Return scalar.
--> 132     return _coerce_scalar_to_timedelta_type(arg, unit=unit, errors=errors)
    133 
    134 

~\.conda\envs\nh4gruv\lib\site-packages\pandas\core\tools\timedeltas.py in _coerce_scalar_to_timedelta_type(r, unit, errors)
    136     """Convert string 'r' to a timedelta object."""
    137     try:
--> 138         result = Timedelta(r, unit)
    139     except ValueError:
    140         if errors == "raise":

pandas\_libs\tslibs\timedeltas.pyx in pandas._libs.tslibs.timedeltas.Timedelta.__new__()

pandas\_libs\tslibs\timedeltas.pyx in pandas._libs.tslibs.timedeltas.parse_timedelta_string()

ValueError: only leading negative signs are allowed
```
I'm pretty certain i found the problem:
`pd.infer_freq()` may produces results, that are not recognized by `pd.to_timedelta()` even after adding a leading '1'.
In my case i use a dataset with a 'W-MON' frequency, which is recognized as such by `pd.infer_freq()`. It then correctly gets changed to '1W-MON', however `pd.to_timedelta()` does not recognize '1W-MON' only '1W', which results in the error seen above.

I implemented a (ugly) fix in my local copy but this problem may result in errors for more users of your library than just me so it might be worth looking into.

Cheers!

**Comment by NHoose** [comment]
To add to this:
Simply changing '1W-MON' to '1W' doesn't really help either as pandas interprets '1W' as being '1W-SUN' and not '7D'. This generates issues down the road, for example in `BaseDataset._load_or_create_xarray_dataset()`:
```
# make sure the df covers the full date range from warmup_start_date to end_date, filling any gaps
# with NaNs. This may increase runtime, but is a very robust way to make sure dates and predictions
# keep in sync. In training, the introduced NaNs will be discarded, so this only affects evaluation.
full_range = pd.date_range(start=warmup_start_date, end=end_date, freq=native_frequency)
df_sub = df_sub.reindex(pd.DatetimeIndex(full_range, name=df_sub.index.name))
```
`full_range` now is in '1W' aka '1W-SUN' freq which results in an index not matching the original 'W-MON' index and therefore a df with only 'NaN'.

Using a 'W-MON' index instead of the more common 'W-SUN' while assembling my dataset might be an oversight by me, however depending on possible 3rd party datasets used this error might occur to more users.

**Comment by gauchm** [comment]
Hi, 
this is actually quite a tricky problem, and worse than I initially thought. As you say, `infer_freq` can produce frequency strings that `to_timedelta` does not understand (see also pandas-dev/pandas#14398, pandas-dev/pandas#36769). 
For `W-MON`, I'd say this is more a bug than a feature (I think a week could safely be interpreted as 7 days, no matter the weekday anchor). But for months, years, etc., it makes sense that the conversion fails, because the delta depends on the specific date it's applied to. 

What's worse, currently the output of `infer_freq` for monthly data, `1M`, gets converted to one _minute_ by `to_timedelta('1M')`, which will certainly cause chaos down the line ([until M, Y, y are deprecated](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_timedelta.html) and no longer work at all).

### Possible Solution
For **single-frequency** use cases, I believe we can use `DateOffset` instead of `TimeDelta`. [`to_offset`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.tseries.frequencies.to_offset.html) supports all the strings that `infer_freq` may return, so we should be able to support arbitrary frequencies this way. 

For **multi-frequency** prediction, we need the `DateOffset`s to be comparable: "how many steps of frequency A fit into one step of frequency B". Some, but not all offsets are comparable: 
- All that worked with `to_timedelta`
- those that are multiples of the same unit, e.g., `1M` and `3M`
- plus some more (`n Y/12n M`, maybe more?)

By refactoring the `frequency_factor` calculations from [various places in our code](https://github.com/neuralhydrology/neuralhydrology/search?q=frequency_factor) into one method that implements these comparisons, we should be able to cover the cases that work now, plus some of the additional cases.

### Ramifications
There is one breaking change all this would cause: The xarray that we save to disk currently uses `TimeDelta` in the `time_step` dimension. This will no longer work, since not every `DateOffset` has a corresponding `TimeDelta`. As a simple solution, we could change the type of `time_step` to integers that represent multiples of the offset. E.g., for a daily+hourly xarray, we'd have `time_steps = [0, 1, ..., 23]` and `datetime = date + time_step * to_offset(freq)`.

---
I've pushed a proof-of-concept of this change to https://github.com/neuralhydrology/neuralhydrology/tree/fix-frequencies. It's still got some rough edges and performance issues (validation/testing will be slower because datetime index calculation isn't vectorized), but I believe it works. Maybe @NHoose you can try if this would work for you?

**Comment by NHoose** [comment]
Hey Martin,

Thanks for the quick response and fix!
Your solution seems to work for the most part and the model trains just fine, however once validation starts, i encounter the following error:
```
UFuncTypeError                            Traceback (most recent call last)
<ipython-input-2-7de041d88ae9> in <module>
----> 1 start_run(config_file=Path("test_config.yml"))

c:\users\nikolas hoose\documents\programmieren\neuralhydrology\neuralhydrology\nh_run.py in start_run(config_file, gpu)
     74         config.device = "cpu"
     75 
---> 76     start_training(config)
     77 
     78 

c:\users\nikolas hoose\documents\programmieren\neuralhydrology\neuralhydrology\training\train.py in start_training(cfg)
     21         raise ValueError(f"Unknown head {cfg.head}.")
     22     trainer.initialize_training()
---> 23     trainer.train_and_validate()

c:\users\nikolas hoose\documents\programmieren\neuralhydrology\neuralhydrology\training\basetrainer.py in train_and_validate(self)
    212 
    213             if (self.validator is not None) and (epoch % self.cfg.validate_every == 0):
--> 214                 self.validator.evaluate(epoch=epoch,
    215                                         save_results=self.cfg.save_validation_results,
    216                                         metrics=self.cfg.metrics,

c:\users\nikolas hoose\documents\programmieren\neuralhydrology\neuralhydrology\evaluation\tester.py in evaluate(self, epoch, save_results, metrics, model, experiment_logger)
    266                             .stack(datetime=['date', 'time_step'])[f"{target_variable}_obs"]
    267                         # TODO performance (also for sim below)
--> 268                         obs['datetime'] = [
    269                             date + time_step * to_offset(freq)
    270                             for date, time_step in zip(obs.coords['date'].values, obs.coords['time_step'].values)

c:\users\nikolas hoose\documents\programmieren\neuralhydrology\neuralhydrology\evaluation\tester.py in <listcomp>(.0)
    267                         # TODO performance (also for sim below)
    268                         obs['datetime'] = [
--> 269                             date + time_step * to_offset(freq)
    270                             for date, time_step in zip(obs.coords['date'].values, obs.coords['time_step'].values)
    271                         ]

UFuncTypeError: ufunc 'add' cannot use operands with types dtype('<M8[ns]') and dtype('O')
```

I will look into this myself, but i thought i'll let you know asap as you know your code way better than i do.
If it helps, here are the current states of the relevant variables:
```
(Pdb) p obs.coords['date'].values
array(['2016-01-04T00:00:00.000000000', '2016-01-11T00:00:00.000000000',
       '2016-01-18T00:00:00.000000000', '2016-01-25T00:00:00.000000000',
       '2016-02-01T00:00:00.000000000', '2016-02-08T00:00:00.000000000',
       '2016-02-15T00:00:00.000000000', '2016-02-22T00:00:00.000000000',
       '2016-02-29T00:00:00.000000000', '2016-03-07T00:00:00.000000000',
       '2016-03-14T00:00:00.000000000', '2016-03-21T00:00:00.000000000',
       '2016-03-28T00:00:00.000000000', '2016-04-04T00:00:00.000000000',
       '2016-04-11T00:00:00.000000000', '2016-04-18T00:00:00.000000000',
       '2016-04-25T00:00:00.000000000', '2016-05-02T00:00:00.000000000',
       '2016-05-09T00:00:00.000000000', '2016-05-16T00:00:00.000000000',
       '2016-05-23T00:00:00.000000000', '2016-05-30T00:00:00.000000000',
       '2016-06-06T00:00:00.000000000', '2016-06-13T00:00:00.000000000',
       '2016-06-20T00:00:00.000000000', '2016-06-27T00:00:00.000000000',
       '2016-07-04T00:00:00.000000000', '2016-07-11T00:00:00.000000000',
       '2016-07-18T00:00:00.000000000', '2016-07-25T00:00:00.000000000',
       '2016-08-01T00:00:00.000000000', '2016-08-08T00:00:00.000000000',
       '2016-08-15T00:00:00.000000000', '2016-08-22T00:00:00.000000000',
       '2016-08-29T00:00:00.000000000', '2016-09-05T00:00:00.000000000',
       '2016-09-12T00:00:00.000000000', '2016-09-19T00:00:00.000000000',
       '2016-09-26T00:00:00.000000000', '2016-10-03T00:00:00.000000000',
       '2016-10-10T00:00:00.000000000', '2016-10-17T00:00:00.000000000',
       '2016-10-24T00:00:00.000000000', '2016-10-31T00:00:00.000000000',
       '2016-11-07T00:00:00.000000000', '2016-11-14T00:00:00.000000000',
       '2016-11-21T00:00:00.000000000', '2016-11-28T00:00:00.000000000',
       '2016-12-05T00:00:00.000000000', '2016-12-12T00:00:00.000000000',
       '2016-12-19T00:00:00.000000000', '2016-12-26T00:00:00.000000000'],
      dtype='datetime64[ns]')
```
```
(Pdb) p obs.coords['time_step'].values
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)
```
```
(Pdb) p to_offset(freq)
<Week: weekday=0>
```

I'll let you know, if i find out anything new.
Thanks again!

**Comment by gauchm** [comment]
Hm, weird -- I'm not getting that error. Maybe something about different numpy or pandas versions. Doesn't matter though, because the calculation of the datetime index wasn't good anyways (wasn't vectorized and therefore slow). 

I just pushed an update to the `fix-frequencies` branch that uses a different logic to calculate the datetime index. It appears to work for the base cases (single-frequency prediction, daily+hourly prediction), but I'm not entirely sure yet if it works for all corner cases. Let me know if you have any issues with it.

**Comment by NHoose** [comment]
Everything seems to work great now, thanks a lot!

**Comment by gauchm** [comment]
(Reopening, since GitHub auto-closing was a bit too eager to close it just yet. The fix will land with our next code update though, which should happen very soon.)
