### ISSUE TITLE
GPU 

### ISSUE THREAD

**Issue by AgroMet** [neuralhydrology/neuralhydrology#43]
torch.cuda.is_available() 
True

But running with cuda:0:
Found GPU%d %s which is of cuda capability %d.%d.
PyTorch no longer supports this GPU because it is too old.
The minimum cuda capability supported by this library is %d.%d.

GPU info:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.06    Driver Version: 450.51.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K20m          Off  | 00000000:03:00.0 Off |                    0 |
| N/A   23C    P0    46W / 225W |      0MiB /  4743MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K20m          Off  | 00000000:83:00.0 Off |                    0 |
| N/A   23C    P0    49W / 225W |      0MiB /  4743MiB |     74%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

**Comment by gauchm** [comment]
Hi, 
unfortunately, your K20m GPU is too old to be supported by recent versions of PyTorch. The K20 has a [CUDA capability of 3.5](https://www.techpowerup.com/gpu-specs/tesla-k20m.c2029), and (I think) the support for that [was dropped with PyTorch 1.3.1](https://github.com/pytorch/pytorch/issues/30532).
If you have access to a more recent GPU, that would certainly be the easiest solution. Otherwise, to try solving this issue, you can install PyTorch 1.3.0 (you might even need to go down to 1.2.0). However, I am not sure whether `neuralhydrology` uses features that did not yet exist in that version, or that have been changed since then. It may well be that some tweaks to the `neuralhydrology` codebase are necessary to get everything running on such an old PyTorch version, or that some things won't work properly.

If all else fails, you might have to stick with running on CPU instead.
