### ISSUE TITLE
Finetuning using pre-trained models

### ISSUE THREAD

**Issue by Meelisha** [neuralhydrology/neuralhydrology#48]
Hello!

I am following the tutorial on training and finetuning the models. I was wondering if it was possible to finetune the  <html> <a href = "https://www.hydroshare.org/resource/83ea5312635e44dc824eeb99eda12f06/" target = "_self">pre-trained models</a></html>? Training the model prior to finetuning with number of epochs takes fairly long time. So, can we simply finetune the pre-trained models by defining a configuration file ?

Thank you!

**Comment by kratzert** [comment]
Hi @Meelisha 

The runs that you are referring to were trained with a different (old and depricated) codebase, which you can find here [https://github.com/kratzert/ealstm_regional_modeling](https://github.com/kratzert/ealstm_regional_modeling).
That said, the models/weights from these files are not straight-forward to fine-tune with this Python package (i.e. neuralHydrology). Since the architecture of the underlying model has not changed (just the names and structure of the layers in the Python class) you could theoretically copy the weights into a model from neuralHydrology that you manually create in e.g. a Python notebook (and then save the new neuralHydrology compatible structure to disk). However, I think that is not what you want to do.

What you could do instead is to take pre-trained models from here: [https://zenodo.org/record/4095485](https://zenodo.org/record/4095485) (see `models-naive.tar.gz` and look at the corresponding [paper](https://hess.copernicus.org/articles/25/2045/2021/)) or here [https://zenodo.org/record/4670268](https://zenodo.org/record/4670268) ([link])(https://hess.copernicus.org/articles/25/2685/2021) to the corresponding paper). Both of these papers did use this codebase to run their experiments and include regionally trained LSTMs for CAMELS US. Fine-tuning these models should be straight-forward (e.g. as described in the Tutorial). 

Let me know if this helps.

**Comment by kratzert** [comment]
Closed due to inactivity. Feel free to re-open if you have any code questions.

**Comment by Meelisha** [comment]
Hi @kratzert !

I did go ahead with fine-tuning using pre-trained MTS-LSTM models https://zenodo.org/record/4670268#.YUoR0OySk2w. However, I am encountering error while loading the pickle file for validation_results.p. Is this something to do with version clash of pandas or xarray?

<img width="756" alt="scrshot of error_pandasIndexError" src="https://user-images.githubusercontent.com/74059522/134226035-bf902eec-64b5-40e1-bbd9-dfdc77af902f.PNG">

Thank you!


> Hi @Meelisha
> 
> The runs that you are referring to were trained with a different (old and depricated) codebase, which you can find here https://github.com/kratzert/ealstm_regional_modeling.
> That said, the models/weights from these files are not straight-forward to fine-tune with this Python package (i.e. neuralHydrology). Since the architecture of the underlying model has not changed (just the names and structure of the layers in the Python class) you could theoretically copy the weights into a model from neuralHydrology that you manually create in e.g. a Python notebook (and then save the new neuralHydrology compatible structure to disk). However, I think that is not what you want to do.
> 
> What you could do instead is to take pre-trained models from here: https://zenodo.org/record/4095485 (see `models-naive.tar.gz` and look at the corresponding [paper](https://hess.copernicus.org/articles/25/2045/2021/)) or here https://zenodo.org/record/4670268 ([link])(https://hess.copernicus.org/articles/25/2685/2021) to the corresponding paper). Both of these papers did use this codebase to run their experiments and include regionally trained LSTMs for CAMELS US. Fine-tuning these models should be straight-forward (e.g. as described in the Tutorial).
> 
> Let me know if this helps.


Hi @kratzert !

I did go ahead with fine-tuning using pre-trained MTS-LSTM models from here: https://zenodo.org/record/4670268#.YUoR0OySk2w. However, I am encountering error while loading the pickle file for validation_results.p. Do you think this is a version clash error for pandas or xarray?

<img width="756" alt="scrshot of error_pandasIndexError" src="https://user-images.githubusercontent.com/74059522/134226609-811f817c-7b41-47d4-822f-e47140866adb.PNG">

Thank you!

**Comment by kratzert** [comment]
Hmm yeah, that is a problem with the pickle version. There are at times problems with opening a pickle file that was stored with an old pickle version. I'll check with @gauchm (who is busy at the moment and might take a while to respond), which version he had installed. You could then downgrade to that version and it should work. We also opened an internal issue to get entirely rid of pickle to avoid such problems in the future.

**Comment by Meelisha** [comment]
I looked up the version for pickle and they were same. But I went forward with installing xarray version used in the above mentioned environment. It works but there is definite version clash and while trying to load files created using newer versions give the same error. I created different environments so that I could load the validation results generated by using recent versions. Thank you for your quick response. Highly appreciate it!
