### ISSUE TITLE
Pre-training on CAMELS dataset and finetuning with generic dataset

### ISSUE THREAD

**Issue by Meelisha** [neuralhydrology/neuralhydrology#65]
Hi there!

I have trained a model with generic dataset which worked pretty well. But, the dataset has very few number of basins, so I wanted to finetune a model with this generic dataset and initialize with weights from pre-trained model with 531 basins of the CAMELS dataset. However, I am encountering an error that says:

KeyError: "None of [Index(['dayl', 'prcp', 'srad', 'tmax', 'tmin', 'vp', 'QObs'], dtype='object')] are in the [columns]"

The forcings data are stored in .nc file with forcing variable name as shown above. My question is do we have to store the data in a different format for the code to run? How should I approach this problem? 

Thank you!

**Comment by Meelisha** [comment]
So I tried to change the variable names from above to [dayl(s) prcp(mm/day) srad(W/m2) swe(mm) tmax(C) tmin(C) vp(Pa)]. However, due to netcdf's naming convention limitations, I couldn't use "/" in the variable name of a netcdf. So, I only changed the rest of the variables that didn't have "/" and it gave the following error:

KeyError: "['prcp', 'srad', 'QObs'] not in index"

Do we have to change the variable names for the finetuning dataset to something same as the pre-training dataset? Will that work? One issue is netcdf doesn't allow "/" in their naming conventions.

**Comment by Meelisha** [comment]
Hi @kratzert !

Thank you for your reply. I apologize for the lack of problem description. I have attached a zip file that contains config file for pre-training, a netcdf file containing forcings data and discharge observation as well as the config file for finetuning. 

For pre-training:
Data used: CAMELS dataset
Forcings dataset: daymet
dynamic input: all except SWE
static input: elevation, slope and area

For finetuing:
Data: generic
Forcings dataset: daymet
dynamic input: all except SWE
static input: elevation, slope and area

[finetune_RGbasins.zip](https://github.com/neuralhydrology/neuralhydrology/files/7891769/finetune_RGbasins.zip)
 
Please let me know if you need more input on this. Again, thank you very much for your help.

**Comment by gauchm** [comment]
Hi @Meelisha,
Thanks for providing more details. As @kratzert said, `/` is not allowed in netCDF, so there's nothing we can do on this end.

If you change the names of input variables from pretraining to finetuning, you'll need to update the names in the finetuning config (as you already did), but you'll also have to update the names in the scaler file (`train_data/train_data_scaler.yml` in the pretraining run directory (*)). I've tried updating the variable names there, too, and could run your finetuning config without a problem.

(*) if you have a pickle instead of yaml file in this place, please consider updating your NeuralHydrology version. If you can't/don't want to do so, you can also edit the variable names by loading the pickle file in python and dumping it again.

One last note: If you come along more exceptions in the future, please also provide the full stack trace (all the stuff that appears on the console before the exception). This makes it a lot easier for us to understand what's happening.

**Comment by Meelisha** [comment]
Thank you @gauchm !!!

This was very helpful. I will definitely post all the details, if I encounter any more exceptions. Thank you for the suggestion.

**Comment by Corinna-Frank** [comment]
Hello @Meelisha,

I encountered the same issue when trying to name the netcdf variables with "/" in the name. The following worked for me:
Generated generic dataset using xarray package, then save to a netcdf with the option `engine="scipy"` like so

`ds.to_netcdf(os.path.join(netcdf_folder,'mybasin.nc'), engine="scipy")`

Hope this will help someone in the future!
